language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: nightly

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - ./vendor/bin/phpunit -v -c Tests/
  - ./vendor/bin/phpcs --config-set default_standard PSR2
  - ./vendor/bin/phpcs src/ Tests/
